import type { Question } from '../types/quiz';

export const INITIAL_50_QUESTIONS: Question[] = [
  // =================== SET 1: क्याम्पस, शिक्षा र शैक्षिक ज्ञान (10 Questions) ===================
  {
    id: 'q1_1',
    quizId: 'quiz_week_12',
    setNumber: 1,
    question: 'त्रिभुवन विश्वविद्यालय (TU) को स्थापना कुन वर्ष भएको हो?',
    optionA: 'वि.सं. २०१३',
    optionB: 'वि.सं. २०१६',
    optionC: 'वि.सं. २०१९',
    optionD: 'वि.सं. २०२८',
    correctAnswer: 'B',
    explanation: 'नेपालको पहिलो विश्वविद्यालय त्रिभुवन विश्वविद्यालयको स्थापना वि.सं. २०१६ असार ११ गते भएको हो।'
  },
  {
    id: 'q1_2',
    quizId: 'quiz_week_12',
    setNumber: 1,
    question: 'स्ववियु (FSU) को पूर्ण रूप के हो?',
    optionA: 'स्वतन्त्र विद्यार्थी सङ्गठन',
    optionB: 'स्वतन्त्र विद्यार्थी युनियन',
    optionC: 'संयुक्त विद्यार्थी युनियन',
    optionD: 'स्वतन्त्र क्याम्पस युनियन',
    correctAnswer: 'B',
    explanation: 'FSU को पूर्ण रूप Free Students Union (स्वतन्त्र विद्यार्थी युनियन) हो।'
  },
  {
    id: 'q1_3',
    quizId: 'quiz_week_12',
    setNumber: 1,
    question: 'नेपालमा हाल औपचारिक रूपमा विद्यालय शिक्षाको संरचना कस्तो रहेको छ?',
    optionA: '१०+२',
    optionB: '५+३+२+२',
    optionC: '८+४',
    optionD: '६+४+२',
    correctAnswer: 'C',
    explanation: 'राष्ट्रिय शिक्षा नीति अनुसार आधारभूत तह (कक्षा १-८) र माध्यमिक तह (कक्षा ९-१२) गरी ८+४ को संरचना छ।'
  },
  {
    id: 'q1_4',
    quizId: 'quiz_week_12',
    setNumber: 1,
    question: 'नेपालमा दरबार हाई स्कुलको स्थापना कसको पालामा भएको थियो?',
    optionA: 'जङ्गबहादुर राणा',
    optionB: 'चन्द्र शमशेर',
    optionC: 'वीर शमशेर',
    optionD: 'देव शमशेर',
    correctAnswer: 'A',
    explanation: 'वि.सं. १९१० मा प्रधानमन्त्री जङ्गबहादुर राणाले बेलायत भ्रमणबाट फर्केपछि दरबार हाई स्कुल स्थापना गरेका थिए।'
  },
  {
    id: 'q1_5',
    quizId: 'quiz_week_12',
    setNumber: 1,
    question: 'त्रिचन्द्र कलेजको स्थापना कुन राणा प्रधानमन्त्रीको कार्यकालमा भएको थियो?',
    optionA: 'रणोद्दीप सिंह',
    optionB: 'चन्द्र शमशेर',
    optionC: 'जुद्ध शमशेर',
    optionD: 'पद्म शमशेर',
    correctAnswer: 'B',
    explanation: 'वि.सं. १९७५ मा प्रधानमन्त्री चन्द्र शमशेरको पालामा त्रिचन्द्र कलेज स्थापना भएको थियो।'
  },
  {
    id: 'q1_6',
    quizId: 'quiz_week_12',
    setNumber: 1,
    question: 'विश्व शिक्षक दिवस हरेक वर्ष कुन मितिमा मनाइन्छ?',
    optionA: 'अक्टोबर ५',
    optionB: 'सेप्टेम्बर ५',
    optionC: 'नोभेम्बर १५',
    optionD: 'डिसेम्बर १०',
    correctAnswer: 'A',
    explanation: 'अन्तर्राष्ट्रिय रूपमा युनेस्कोद्वारा हरेक वर्ष अक्टोबर ५ लाई विश्व शिक्षक दिवसका रूपमा मनाइन्छ।'
  },
  {
    id: 'q1_7',
    quizId: 'quiz_week_12',
    setNumber: 1,
    question: 'नेपालको पहिलो महिला प्राध्यापक को हुन्?',
    optionA: 'पारिजात',
    optionB: 'कमल दीक्षित',
    optionC: 'अङ्गुरबाबा जोशी',
    optionD: 'सुशीला कार्की',
    correctAnswer: 'C',
    explanation: 'अङ्गुरबाबा जोशी नेपालको पहिलो महिला क्याम्पस प्रमुख तथा वरिष्ठ प्राध्यापक हुन्।'
  },
  {
    id: 'q1_8',
    quizId: 'quiz_week_12',
    setNumber: 1,
    question: 'विश्वविद्यालय अनुदान आयोग (UGC Nepal) को मुख्य कार्य के हो?',
    optionA: 'विद्यार्थीलाई राहदानी जारी गर्ने',
    optionB: 'उच्च शिक्षा संस्थाहरूको गुणस्तर सुधार र अनुदान व्यवस्थापन',
    optionC: 'पाठ्यपुस्तक बिक्री गर्ने',
    optionD: 'कक्षा १० को परीक्षा लिने',
    correctAnswer: 'B',
    explanation: 'UGC ले नेपालका विश्वविद्यालय तथा क्याम्पसहरूको शैक्षिक गुणस्तर अभिवृद्धि तथा आर्थिक अनुदान व्यवस्थापन गर्दछ।'
  },
  {
    id: 'q1_9',
    quizId: 'quiz_week_12',
    setNumber: 1,
    question: 'राष्ट्रिय शिक्षा दिवस नेपालमा हाल कुन ऐतिहासिक अवसरमा मनाइन्छ?',
    optionA: 'फागुन ७',
    optionB: 'असोज २',
    optionC: 'माघ १६',
    optionD: 'वैशाख १',
    correctAnswer: 'B',
    explanation: 'अनिवार्य तथा निःशुल्क शिक्षा ऐन प्रमाणीकरण भएको दिन असोज २ गतेलाई राष्ट्रिय शिक्षा दिवसका रूपमा मनाइन्छ।'
  },
  {
    id: 'q1_10',
    quizId: 'quiz_week_12',
    setNumber: 1,
    question: 'विश्व साक्षरता दिवस कहिले मनाइन्छ?',
    optionA: 'सेप्टेम्बर ८',
    optionB: 'अगस्ट १२',
    optionC: 'जुलाई २०',
    optionD: 'अक्टोबर २४',
    correctAnswer: 'A',
    explanation: 'संयुक्त राष्ट्रसंघीय निकाय युनेस्कोले हरेक वर्ष सेप्टेम्बर ८ मा अन्तर्राष्ट्रिय साक्षरता दिवस मनाउँछ।'
  },

  // =================== SET 2: नेपाली साहित्य, संस्कृति र इतिहास (10 Questions) ===================
  {
    id: 'q2_1',
    quizId: 'quiz_week_12',
    setNumber: 2,
    question: 'नेपाली भाषाका आदिकवि भनेर कसलाई चिनिन्छ?',
    optionA: 'लक्ष्मीप्रसाद देवकोटा',
    optionB: 'भानुभक्त आचार्य',
    optionC: 'मोतीराम भट्ट',
    optionD: 'लेखनाथ पौड्याल',
    correctAnswer: 'B',
    explanation: 'रामायणलाई सरल नेपाली पद्यमा अनुवाद गर्ने भानुभक्त आचार्यलाई आदिकवि मानिन्छ।'
  },
  {
    id: 'q2_2',
    quizId: 'quiz_week_12',
    setNumber: 2,
    question: 'प्रसिद्ध खण्डकाव्य "मुनामदन" का रचनाकार को हुन्?',
    optionA: 'माधवप्रसाद घिमिरे',
    optionB: 'गोपालप्रसाद रिमाल',
    optionC: 'लक्ष्मीप्रसाद देवकोटा',
    optionD: 'बालकृष्ण सम',
    correctAnswer: 'C',
    explanation: 'महाकवि लक्ष्मीप्रसाद देवकोटाले वि.सं. १९९२ मा झ्याउरे लयमा मुनामदन रचना गरेका थिए।'
  },
  {
    id: 'q2_3',
    quizId: 'quiz_week_12',
    setNumber: 2,
    question: 'मदन पुरस्कार पाउने पहिलो उपन्यास कुन हो?',
    optionA: 'शिरीषको फूल',
    optionB: 'मन',
    optionC: 'बसाइँ',
    optionD: 'घामका पाइलाहरू',
    correctAnswer: 'B',
    explanation: 'लीलध्वज थापाको उपन्यास "मन" ले वि.सं. २०१४ सालमा मदन पुरस्कार प्राप्त गरेको थियो।'
  },
  {
    id: 'q2_4',
    quizId: 'quiz_week_12',
    setNumber: 2,
    question: 'नेपालको राष्ट्रिय गान "सयौँ थुँगा फूलका हामी" का रचनाकार को हुन्?',
    optionA: 'अम्बर गुरुङ',
    optionB: 'प्रदीपकुमार राई (व्याकुल माइला)',
    optionC: 'युगकवि सिद्धिचरण श्रेष्ठ',
    optionD: 'धर्मराज थापा',
    correctAnswer: 'B',
    explanation: 'गीतकार प्रदीपकुमार राई (व्याकुल माइला) ले राष्ट्रिय गान रचना गरेका हुन्, जसमा संगीत अम्बर गुरुङको छ।'
  },
  {
    id: 'q2_5',
    quizId: 'quiz_week_12',
    setNumber: 2,
    question: 'राष्ट्रकवि माधवप्रसाद घिमिरेको प्रसिद्ध गीतिनाटक कुन हो?',
    optionA: 'मालती मङ्गले',
    optionB: 'गौरी',
    optionC: 'शकुन्तला',
    optionD: 'कुञ्जिनी',
    correctAnswer: 'A',
    explanation: 'राष्ट्रकवि माधवप्रसाद घिमिरेद्वारा रचित "मालती मङ्गले" एक अत्यन्त लोकप्रिय गीतिनाटक हो।'
  },
  {
    id: 'q2_6',
    quizId: 'quiz_week_12',
    setNumber: 2,
    question: 'काठमाडौँ उपत्यकाको प्रसिद्ध "इन्द्रजात्रा" कसले सुरु गरेका मानिन्छ?',
    optionA: 'राजा गुणकामदेव',
    optionB: 'राजा जयस्थिति मल्ल',
    optionC: 'राजा प्रताप मल्ल',
    optionD: 'राजा यक्ष मल्ल',
    correctAnswer: 'A',
    explanation: 'ऐतिहासिक मान्यता अनुसार कान्तिपुरका राजा गुणकामदेवले इन्द्रजात्राको सुरुआत गरेका हुन्।'
  },
  {
    id: 'q2_7',
    quizId: 'quiz_week_12',
    setNumber: 2,
    question: 'नेपाल संवत्का प्रवर्तक को हुन्?',
    optionA: 'अंशुवर्मा',
    optionB: 'शंखधर साख्वा',
    optionC: 'अरि मल्ल',
    optionD: 'जनक',
    correctAnswer: 'B',
    explanation: 'शंखधर साख्वाले गरिब जनताको ऋण मोचन गरी वि.सं. ९३६ (सन् ८७९) मा नेपाल संवत् सुरु गरेका थिए।'
  },
  {
    id: 'q2_8',
    quizId: 'quiz_week_12',
    setNumber: 2,
    question: 'नेपाली साहित्यमा "युगकवि" भनेर कुन स्रष्टालाई सम्बोधन गरिन्छ?',
    optionA: 'सिद्धिचरण श्रेष्ठ',
    optionB: 'भूपि शेरचन',
    optionC: 'भवानी भिक्षु',
    optionD: 'भवानीप्रसाद घिमिरे',
    correctAnswer: 'A',
    explanation: 'नेपाली साहित्यमा सिद्धिचरण श्रेष्ठलाई क्रान्तिकारी चेतनाका धनी "युगकवि" मानिन्छ।'
  },
  {
    id: 'q2_9',
    quizId: 'quiz_week_12',
    setNumber: 2,
    question: 'सुगौली सन्धिमा नेपालको तर्फबाट कसले हस्ताक्षर गरेका थिए?',
    optionA: 'अमरसिंह थापा',
    optionB: 'गजराज मिश्र र चन्द्रशेखर उपाध्याय',
    optionC: 'भीमसेन थापा',
    optionD: 'रणबहादुर शाह',
    correctAnswer: 'B',
    explanation: 'सन् १८१६ को सुगौली सन्धिमा नेपाल पक्षबाट गजराज मिश्र र चन्द्रशेखर उपाध्यायले हस्ताक्षर गरेका थिए।'
  },
  {
    id: 'q2_10',
    quizId: 'quiz_week_12',
    setNumber: 2,
    question: 'प्रसिद्ध उपन्यास "शिरीषको फूल" का लेखक को हुन्?',
    optionA: 'पारिजात',
    optionB: 'तारानाथ शर्मा',
    optionC: 'ध.च. गोतामे',
    optionD: 'डायमण्ड शमशेर',
    correctAnswer: 'A',
    explanation: 'पारिजात (विष्णुकुमारी वाइबा) ले वि.सं. २०२२ मा शिरीषको फूल लेखी मदन पुरस्कार पाएकी थिइन्।'
  },

  // =================== SET 3: विज्ञान, सूचना प्रविधि र आधुनिक आविष्कार (10 Questions) ===================
  {
    id: 'q3_1',
    quizId: 'quiz_week_12',
    setNumber: 3,
    question: 'कम्प्युटरको मस्तिष्क (Brain of Computer) भनेर कुन भागलाई चिनिन्छ?',
    optionA: 'RAM',
    optionB: 'Hard Disk',
    optionC: 'CPU (Central Processing Unit)',
    optionD: 'Motherboard',
    correctAnswer: 'C',
    explanation: 'CPU ले कम्प्युटरका सम्पूर्ण गणना र निर्देशनहरू प्रशोधन गर्ने भएकाले यसलाई मस्तिष्क भनिन्छ।'
  },
  {
    id: 'q3_2',
    quizId: 'quiz_week_12',
    setNumber: 3,
    question: 'इन्टरनेटमा वेबसाइट पहिचान गर्न प्रयोग गरिने URL को पूर्ण रूप के हो?',
    optionA: 'Uniform Resource Locator',
    optionB: 'Universal Radio Link',
    optionC: 'Unified Record Language',
    optionD: 'Unique Remote Location',
    correctAnswer: 'A',
    explanation: 'URL को अर्थ Uniform Resource Locator हो जसले वेब स्रोतको ठेगाना देखाउँछ।'
  },
  {
    id: 'q3_3',
    quizId: 'quiz_week_12',
    setNumber: 3,
    question: 'नेपालको आफ्नै पहिलो नानो-स्याटेलाइटको नाम के हो?',
    optionA: 'नेपाली स्याट-१ (NepaliSat-1)',
    optionB: 'सगरमाथा-१',
    optionC: 'डाँफे-१',
    optionD: 'गौतम बुद्ध स्याट',
    correctAnswer: 'A',
    explanation: 'नेपाल विज्ञान तथा प्रविधि प्रज्ञा प्रतिष्ठान (NAST) को पहलमा सन् २०१९ अप्रिलमा NepaliSat-1 प्रक्षेपण गरिएको थियो।'
  },
  {
    id: 'q3_4',
    quizId: 'quiz_week_12',
    setNumber: 3,
    question: 'सूर्यको प्रकाश पृथ्वीसम्म आइपुग्न लगभग कति समय लाग्छ?',
    optionA: '५ मिनेट',
    optionB: '८ मिनेट २० सेकेन्ड',
    optionC: '१० मिनेट',
    optionD: '१२ मिनेट ३० सेकेन्ड',
    correctAnswer: 'B',
    explanation: 'सूर्यबाट प्रकाश पृथ्वीसम्म आउन करिब ५०० सेकेन्ड अर्थात् ८ मिनेट २० सेकेन्ड लाग्दछ।'
  },
  {
    id: 'q3_5',
    quizId: 'quiz_week_12',
    setNumber: 3,
    question: 'मानव शरीरमा सबैभन्दा ठूलो ग्रन्थी (Largest Gland) कुन हो?',
    optionA: 'मुटु (Heart)',
    optionB: 'कलेजो (Liver)',
    optionC: 'प्यान्क्रियाज (Pancreas)',
    optionD: 'मृगौला (Kidney)',
    correctAnswer: 'B',
    explanation: 'मानव शरीरको सबैभन्दा ठूलो आन्तरिक अङ्ग तथा ग्रन्थी कलेजो (Liver) हो।'
  },
  {
    id: 'q3_6',
    quizId: 'quiz_week_12',
    setNumber: 3,
    question: 'गुरुत्वाकर्षणको नियम (Law of Universal Gravitation) कसले पत्ता लगाएका हुन्?',
    optionA: 'अल्बर्ट आइन्स्टाइन',
    optionB: 'सर आइज्याक न्युटन',
    optionC: 'ग्यालिलियो ग्यालिली',
    optionD: 'निकोलस कोपर्निकस',
    correctAnswer: 'B',
    explanation: 'स्याउ खसेको अवलोकन गर्दै सर आइज्याक न्युटनले गुरुत्वाकर्षण सिद्धान्त प्रतिपादन गरेका थिए।'
  },
  {
    id: 'q3_7',
    quizId: 'quiz_week_12',
    setNumber: 3,
    question: 'आधुनिक मोबाइल फोनमा प्रयोग गरिने सिमसँग सम्बन्धित eSIM को "e" ले के जनाउँछ?',
    optionA: 'Electronic',
    optionB: 'Embedded',
    optionC: 'External',
    optionD: 'Enhanced',
    correctAnswer: 'B',
    explanation: 'eSIM को पूर्ण रूप Embedded Subscriber Identity Module हो।'
  },
  {
    id: 'q3_8',
    quizId: 'quiz_week_12',
    setNumber: 3,
    question: 'पानीको रासायनिक सूत्र (Chemical Formula) के हो?',
    optionA: 'CO2',
    optionB: 'H2O',
    optionC: 'NaCl',
    optionD: 'CH4',
    correctAnswer: 'B',
    explanation: 'पानी दुईवटा हाइड्रोजन र एउटा अक्सिजन अणु मिलेर बन्दछ (H2O)।'
  },
  {
    id: 'q3_9',
    quizId: 'quiz_week_12',
    setNumber: 3,
    question: 'कृत्रिम बौद्धिकता (AI - Artificial Intelligence) का पिता भनेर कसलाई मानिन्छ?',
    optionA: 'जोन म्याकार्थी (John McCarthy)',
    optionB: 'एलन ट्युरिङ (Alan Turing)',
    optionC: 'चार्ल्स ब्याबेज (Charles Babbage)',
    optionD: 'बिल गेट्स (Bill Gates)',
    correctAnswer: 'A',
    explanation: 'सन् १९५६ मा AI शब्दको पहिलो प्रयोग गर्ने वैज्ञानिक जोन म्याकार्थीलाई AI का पिता मानिन्छ।'
  },
  {
    id: 'q3_10',
    quizId: 'quiz_week_12',
    setNumber: 3,
    question: 'कम्प्युटर सञ्जालमा IPv4 ठेगाना (Address) कति बिटको हुन्छ?',
    optionA: '१६ बिट',
    optionB: '३२ बिट',
    optionC: '६४ बिट',
    optionD: '१२८ बिट',
    correctAnswer: 'B',
    explanation: 'IPv4 ठेगाना ३२ बिट (४ बाइट) को हुन्छ जबकि IPv6 ठेगाना १२८ बिटको हुन्छ।'
  },

  // =================== SET 4: नेपालको भूगोल, सम्पदा र वातावरण (10 Questions) ===================
  {
    id: 'q4_1',
    quizId: 'quiz_week_12',
    setNumber: 4,
    question: 'संसारको सर्वोच्च शिखर सगरमाथाको पछिल्लो आधिकारिक उचाइ कति कायम गरिएको छ?',
    optionA: '८,८४८ मिटर',
    optionB: '८,८४८.८६ मिटर',
    optionC: '८,८५० मिटर',
    optionD: '८,८४६ मिटर',
    correctAnswer: 'B',
    explanation: 'नेपाल र चीनद्वारा २०७७ मङ्सिर २३ मा संयुक्त रूपमा घोषित आधिकारिक उचाइ ८,८४८.८६ मिटर हो।'
  },
  {
    id: 'q4_2',
    quizId: 'quiz_week_12',
    setNumber: 4,
    question: 'नेपालको सबैभन्दा ठूलो ताल कुन हो?',
    optionA: 'फेवा ताल',
    optionB: 'रारा ताल',
    optionC: 'फोक्सुन्डो ताल',
    optionD: 'तिलिचो ताल',
    correctAnswer: 'B',
    explanation: 'मुगु जिल्लामा अवस्थित रारा ताल नेपालको क्षेत्रफलका आधारमा सबैभन्दा ठूलो ताल हो।'
  },
  {
    id: 'q4_3',
    quizId: 'quiz_week_12',
    setNumber: 4,
    question: 'नेपालमा कतिवटा प्रदेशहरू रहेका छन्?',
    optionA: '५ वटा',
    optionB: '७ वटा',
    optionC: '१४ वटा',
    optionD: '७५ वटा',
    correctAnswer: 'B',
    explanation: 'नेपालको संविधान (२०७२) अनुसार नेपालमा ७ वटा संघीय प्रदेशहरू रहेका छन्।'
  },
  {
    id: 'q4_4',
    quizId: 'quiz_week_12',
    setNumber: 4,
    question: 'नेपालको पहिलो राष्ट्रिय निकुञ्ज कुन हो?',
    optionA: 'सगरमाथा राष्ट्रिय निकुञ्ज',
    optionB: 'चितवन राष्ट्रिय निकुञ्ज',
    optionC: 'बर्दिया राष्ट्रिय निकुञ्ज',
    optionD: 'लाङटाङ राष्ट्रिय निकुञ्ज',
    correctAnswer: 'B',
    explanation: 'वि.सं. २०३० मा स्थापित चितवन राष्ट्रिय निकुञ्ज नेपालको पहिलो राष्ट्रिय निकुञ्ज हो।'
  },
  {
    id: 'q4_5',
    quizId: 'quiz_week_12',
    setNumber: 4,
    question: 'एकसिङ्गे गैँडाका लागि नेपालको कुन संरक्षित क्षेत्र विश्वप्रसिद्ध छ?',
    optionA: 'चितवन राष्ट्रिय निकुञ्ज',
    optionB: 'रारा राष्ट्रिय निकुञ्ज',
    optionC: 'खप्तड राष्ट्रिय निकुञ्ज',
    optionD: 'मकालु वरुण राष्ट्रिय निकुञ्ज',
    correctAnswer: 'A',
    explanation: 'चितवन राष्ट्रिय निकुञ्ज दुर्लभ एकसिङ्गे गैँडा तथा पाटे बाघको प्रमुख बासस्थान हो।'
  },
  {
    id: 'q4_6',
    quizId: 'quiz_week_12',
    setNumber: 4,
    question: 'नेपालको सबैभन्दा गहिरो नदी कुन हो?',
    optionA: 'कोशी',
    optionB: 'गण्डकी (नारायणी)',
    optionC: 'कर्णाली',
    optionD: 'महाकाली',
    correctAnswer: 'B',
    explanation: 'नेपालको सबैभन्दा गहिरो नदी गण्डकी हो, सबैभन्दा ठूलो कोशी र सबैभन्दा लामो कर्णाली हो।'
  },
  {
    id: 'q4_7',
    quizId: 'quiz_week_12',
    setNumber: 4,
    question: 'भगवान गौतम बुद्धको जन्मस्थल लुम्बिनी कुन जिल्लामा पर्दछ?',
    optionA: 'कपिलवस्तु',
    optionB: 'रुपन्देही',
    optionC: 'नवलपरासी',
    optionD: 'पाल्पा',
    correctAnswer: 'B',
    explanation: 'शान्तिका अग्रदूत गौतम बुद्धको जन्मस्थल ऐतिहासिक लुम्बिनी रुपन्देही जिल्लामा पर्दछ।'
  },
  {
    id: 'q4_8',
    quizId: 'quiz_week_12',
    setNumber: 4,
    question: 'विश्व वातावरण दिवस हरेक वर्ष कुन मितिमा मनाइन्छ?',
    optionA: 'जुन ५',
    optionB: 'अप्रिल २२',
    optionC: 'मे २२',
    optionD: 'मार्च २१',
    correctAnswer: 'A',
    explanation: 'वातावरण संरक्षणमा सचेतना फैलाउन हरेक वर्ष जुन ५ मा विश्व वातावरण दिवस मनाइन्छ।'
  },
  {
    id: 'q4_9',
    quizId: 'quiz_week_12',
    setNumber: 4,
    question: 'नेपालको प्रमाणित प्रमाणिक समय कुन हिमाललाई आधार मानेर निर्धारण गरिएको छ?',
    optionA: 'सगरमाथा',
    optionB: 'गौरीशङ्कर हिमाल',
    optionC: 'मनास्लु',
    optionD: 'अन्नपूर्ण',
    correctAnswer: 'B',
    explanation: 'दोलखा जिल्लाको गौरीशङ्कर हिमाल (८६ डिग्री १५ मिनेट पूर्वी देशान्तर) लाई आधार मानेर वि.सं. २०४२ वैशाख १ देखि समय तय गरिएको हो।'
  },
  {
    id: 'q4_10',
    quizId: 'quiz_week_12',
    setNumber: 4,
    question: 'नेपालको कुल क्षेत्रफल कति वर्ग किलोमिटर रहेको छ?',
    optionA: '१,४७,१८१ वर्ग कि.मि.',
    optionB: '१,४७,५१६ वर्ग कि.मि.',
    optionC: '१,५०,००० वर्ग कि.मि.',
    optionD: '१,४५,३९० वर्ग कि.मि.',
    correctAnswer: 'B',
    explanation: 'नेपालको नयाँ चुच्चे नक्सा सहितको कुल क्षेत्रफल १,४७,५१६ वर्ग किलोमिटर रहेको छ।'
  },

  // =================== SET 5: समसामयिक ज्ञान, खेलकुद र बौद्धिक परीक्षण (10 Questions) ===================
  {
    id: 'q5_1',
    quizId: 'quiz_week_12',
    setNumber: 5,
    question: 'नेपालको राष्ट्रिय खेल कुन हो?',
    optionA: 'फुटबल',
    optionB: 'क्रिकेट',
    optionC: 'भलिबल',
    optionD: 'डण्डीबियो',
    correctAnswer: 'C',
    explanation: 'नेपाल सरकारले वि.सं. २०७४ जेठ ८ गते भलिबललाई नेपालको राष्ट्रिय खेल घोषणा गरेको हो।'
  },
  {
    id: 'q5_2',
    quizId: 'quiz_week_12',
    setNumber: 5,
    question: 'सार्क (SAARC) को स्थायी सचिवालय कहाँ अवस्थित छ?',
    optionA: 'नयाँ दिल्ली, भारत',
    optionB: 'काठमाडौँ, नेपाल',
    optionC: 'ढाका, बङ्गलादेश',
    optionD: 'कोलम्बो, श्रीलङ्का',
    correctAnswer: 'B',
    explanation: 'दक्षिण एसियाली क्षेत्रीय सहयोग सङ्गठन (सार्क) को सचिवालय काठमाडौँको ठमेलमा अवस्थित छ।'
  },
  {
    id: 'q5_3',
    quizId: 'quiz_week_12',
    setNumber: 5,
    question: 'संयुक्त राष्ट्रसंघ (UN) को स्थापना कुन वर्ष भएको थियो?',
    optionA: 'सन् १९१४',
    optionB: 'सन् १९३९',
    optionC: 'सन् १९४५',
    optionD: 'सन् १९५०',
    correctAnswer: 'C',
    explanation: 'दोस्रो विश्वयुद्ध पश्चात् २४ अक्टोबर १९४५ मा संयुक्त राष्ट्रसंघको स्थापना भएको हो।'
  },
  {
    id: 'q5_4',
    quizId: 'quiz_week_12',
    setNumber: 5,
    question: 'हाल नेपालको संविधानमा कतिवटा मौलिक हकहरूको व्यवस्था गरिएको छ?',
    optionA: '२१ वटा',
    optionB: '२५ वटा',
    optionC: '३१ वटा',
    optionD: '३५ वटा',
    correctAnswer: 'C',
    explanation: 'नेपालको वर्तमान संविधानको भाग ३, धारा १६ देखि ४६ सम्म ३१ वटा मौलिक हकहरू व्यवस्था गरिएको छ।'
  },
  {
    id: 'q5_5',
    quizId: 'quiz_week_12',
    setNumber: 5,
    question: 'ओलम्पिक खेलकुदको प्रतीक चिन्हमा रहेका ५ वटा चक्काहरूले के जनाउँछन्?',
    optionA: 'पाँच महादेशहरू',
    optionB: 'पाँच महासागरहरू',
    optionC: 'पाँच प्रमुख खेलहरू',
    optionD: 'पाँच प्रमुख देशहरू',
    correctAnswer: 'A',
    explanation: 'ओलम्पिकका पाँच रङ्गका आपसमा जोडिएका चक्काहरूले विश्वका पाँच प्रमुख महादेशहरूको एकता जनाउँछन्।'
  },
  {
    id: 'q5_6',
    quizId: 'quiz_week_12',
    setNumber: 5,
    question: 'नेपाल राष्ट्र बैंकको स्थापना कहिले भएको थियो?',
    optionA: 'वि.सं. २०१३ वैशाख १४',
    optionB: 'वि.सं. २०१६ असार ११',
    optionC: 'वि.सं. २००७ फागुन ७',
    optionD: 'वि.सं. २०२८ कात्तिक १',
    correctAnswer: 'A',
    explanation: 'नेपालको केन्द्रीय बैंकका रूपमा वि.सं. २०१३ वैशाख १४ गते नेपाल राष्ट्र बैंक स्थापना भएको हो।'
  },
  {
    id: 'q5_7',
    quizId: 'quiz_week_12',
    setNumber: 5,
    question: 'अन्तर्राष्ट्रिय क्रिकेट परिषद् (ICC) द्वारा नेपालले एकदिवसीय अन्तर्राष्ट्रिय (ODI) मान्यता कहिले प्राप्त गरेको थियो?',
    optionA: 'सन् २०१४',
    optionB: 'सन् २०१८',
    optionC: 'सन् २०२२',
    optionD: 'सन् २०२४',
    correctAnswer: 'B',
    explanation: 'नेपाली राष्ट्रिय क्रिकेट टोलीले सन् २०१८ मार्चमा जिम्बावेमा सम्पन्न विश्वकप छनोटमार्फत पहिलोपटक ऐतिहासिक ODI मान्यता पाएको थियो।'
  },
  {
    id: 'q5_8',
    quizId: 'quiz_week_12',
    setNumber: 5,
    question: 'बौद्धिक परीक्षण: तलको क्रममा अर्को संख्या कुन हुन्छ? २, ६, १२, २०, ३०, ?',
    optionA: '३६',
    optionB: '४०',
    optionC: '४२',
    optionD: '४८',
    correctAnswer: 'C',
    explanation: 'अन्तर +४, +६, +८, +१०, +१२ बढ्दै गएको छ (३० + १२ = ४२)।'
  },
  {
    id: 'q5_9',
    quizId: 'quiz_week_12',
    setNumber: 5,
    question: 'नोबेल शान्ति पुरस्कार कहाँ प्रदान गरिन्छ?',
    optionA: 'स्टकहोम, स्विडेन',
    optionB: 'ओस्लो, नर्वे',
    optionC: 'जेनेभा, स्विट्जरल्यान्ड',
    optionD: 'पेरिस, फ्रान्स',
    correctAnswer: 'B',
    explanation: 'अन्य सबै विधाका नोबेल पुरस्कारहरू स्विडेनको स्टकहोममा र नोबेल शान्ति पुरस्कार नर्वेको ओस्लोमा प्रदान गरिन्छ।'
  },
  {
    id: 'q5_10',
    quizId: 'quiz_week_12',
    setNumber: 5,
    question: 'बौद्धिक परीक्षण: यदि "COLLEGE" लाई कूटभाषामा "DPMMFHF" लेखिन्छ भने "CAMPUS" लाई के लेखिन्छ?',
    optionA: 'DBNQVT',
    optionB: 'BDNRVU',
    optionC: 'DCLQVT',
    optionD: 'DBMOVU',
    correctAnswer: 'A',
    explanation: 'प्रत्येक अक्षरलाई वर्णानुक्रममा १ स्थान अगाडि सारिएको छ: C->D, A->B, M->N, P->Q, U->V, S->T (DBNQVT)।'
  }
];
